"""rename address

Revision ID: 562139f96b10
Revises: fa1ff3395e52
Create Date: 2023-12-14 17:24:30.924720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562139f96b10'
down_revision = 'fa1ff3395e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
